target_os = "ios"
target_cpu = "arm64"
target_environment = "simulator"
is_debug = false
is_component_build = false
symbol_level = 1
angle_build_tests = false
build_angle_deqp_tests = false
angle_build_all = false
angle_enable_metal = true
angle_enable_gl = false
angle_enable_vulkan = false
angle_enable_null = false
angle_enable_wgpu = false
angle_has_rapidjson = false
angle_has_frame_capture = false
clang_use_chrome_plugins = false
use_custom_libcxx = false
use_system_xcode = true
use_siso = false
use_remoteexec = false
enable_rust = false
enable_rust_cxx = false
ios_enable_code_signing = false
angle_build_vulkan_system_info = false
angle_enable_perfetto = false
angle_standalone = false
