"""Embed source for runtime Metal compilation; no game files are modified."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]/'port/de'
for name in ['BCBasic','BC6']:
    source=(root/(name+'Kernel.metal')).read_text()
    (root/(name+'Kernel.inc')).write_text('// Generated by scripts/embed-de-bc-kernels.py.\nstatic NSString *const DE'+name+'Kernel=@'+ '\n'.join(json.dumps(line+'\n') for line in source.splitlines())+';\n')
