from pathlib import Path
import re,json,hashlib
root=Path(__file__).resolve().parents[1]
s=(root/'port/de/third_party/bcdec/bcdec.h').read_text()
assert hashlib.sha256(s.encode()).hexdigest()=='622ef8d2e1fad8baf579085f1ff7b0845bdf34143e8d11371530499d1a76152c'
a=s.index('BCDECDEF void bcdec_bc7(',s.index('#ifdef BCDEC_IMPLEMENTATION'))
b=s.index('\n#endif /* BCDEC_IMPLEMENTATION */',a)
f=s[a:b];constants=[]
def constant(m):
 constants.append('constant '+m.group(1)+';');return ''
f=re.sub(r'\n    static ([\s\S]+?);',constant,f)
f=f.replace('BCDECDEF void bcdec_bc7(const void* compressedBlock, void* decompressedBlock, int destinationPitch)', 'inline void decode_block(device const uchar* compressedBlock, thread uchar* decompressedBlock, int destinationPitch)')
f=f.replace('int* weights, * weights2;', 'constant int* weights; constant int* weights2;').replace('unsigned char* decompressed;', 'thread uchar* decompressed;').replace('(unsigned char*)decompressedBlock','decompressedBlock').replace('(const unsigned char*)compressedBlock','compressedBlock')
helpers='''#include <metal_stdlib>
using namespace metal;
struct bcdec__bitstream_t { ulong low,high; };
inline ulong bcdec__getu64le(device const uchar* p){ulong v=0;for(uint i=0;i<8;i++)v|=ulong(p[i])<<(8*i);return v;}
inline int bcdec__bitstream_read_bits(thread bcdec__bitstream_t* b,int n){ulong mask=(1ul<<n)-1;int v=int(b->low&mask);b->low=(b->low>>n)|((b->high&mask)<<(64-n));b->high>>=n;return v;}
inline int bcdec__bitstream_read_bit(thread bcdec__bitstream_t* b){return bcdec__bitstream_read_bits(b,1);}
inline int bcdec__interpolate(int a,int b,constant int* weights,int i){return (a*(64-weights[i])+b*weights[i]+32)>>6;}
inline void bcdec__swap_values(thread int* a,thread int* b){int t=*a;*a=*b;*b=t;}
'''
kernel='''
struct BC7Params { uint stride,width,height,x,y; };
kernel void decode_bc7(device const uchar* src[[buffer(0)]],constant BC7Params& p[[buffer(1)]],texture2d<float,access::write> dst[[texture(0)]],uint2 block[[thread_position_in_grid]]){
 uint2 base=block*4;if(base.x>=p.width||base.y>=p.height)return;
 uchar rgba[64];decode_block(src+ulong(block.y)*p.stride+ulong(block.x)*16,rgba,16);
 for(uint y=0;y<4;y++)for(uint x=0;x<4;x++){uint2 q=base+uint2(x,y);if(q.x>=p.width||q.y>=p.height)continue;uint i=(y*4+x)*4;dst.write(float4(rgba[i],rgba[i+1],rgba[i+2],rgba[i+3])/255.0f,q+uint2(p.x,p.y));}
}
'''
notice='// Derived from pinned MIT bcdec; copyright and license: third_party/bcdec/bcdec.h.\n// Generated by scripts/generate-de-bc7-metal.py; do not edit.\n'
license=s[s.index('Copyright (c) 2022 Sergii Kudlai'):s.index('\n------------------------------------------------------------------------------\nALTERNATIVE B')]
notice+='/* '+license.strip()+' */\n'
shader=notice+helpers+'\n'.join(constants)+'\n'+f+kernel
(root/'port/de/BC7Kernel.metal').write_text(shader)
(root/'port/de/BC7Kernel.inc').write_text('#pragma once\n'+notice+'static NSString *const DEBC7Kernel=@'+ '\n'.join(json.dumps(line+'\n',ensure_ascii=False) for line in shader.splitlines())+';\n')
print('BC7 shader generated',len(shader),'bytes')
