"""Translate the pinned, locally corrected BC6H decoder to a Metal kernel."""
from pathlib import Path
import hashlib
import re

root = Path(__file__).resolve().parents[1]
s = (root / 'port/de/third_party/bcdec/bcdec.h').read_text()
assert hashlib.sha256(s.encode()).hexdigest() == '622ef8d2e1fad8baf579085f1ff7b0845bdf34143e8d11371530499d1a76152c'
helpers = s[s.index('static int bcdec__extend_sign'):s.index('/* modified half_to_float_fast4')]
helpers = helpers.replace('int* weights', 'constant int* weights').replace('static ', 'inline ')
start = s.index('BCDECDEF void bcdec_bc6h_half(', s.index('#ifdef BCDEC_IMPLEMENTATION'))
f = s[start:s.index('BCDECDEF void bcdec_bc6h_float(', start)]
constants = []
def constant(m):
    constants.append('constant ' + m.group(1) + ';')
    return ''
f = re.sub(r'\n    static ([\s\S]+?);', constant, f)
f = f.replace('BCDECDEF void bcdec_bc6h_half(const void* compressedBlock, void* decompressedBlock', 'inline void decode_block(device const uchar* compressedBlock, thread ushort* decompressedBlock')
f = f.replace('unsigned short* decompressed;', 'thread ushort* decompressed;').replace('(unsigned short*)decompressedBlock', 'decompressedBlock')
f = f.replace('int* weights;', 'constant int* weights;').replace('(const unsigned char*)compressedBlock', 'compressedBlock')
prefix = '''#include <metal_stdlib>
using namespace metal;
struct bcdec__bitstream_t { ulong low, high; };
inline ulong bcdec__getu64le(device const uchar* p) { ulong v=0;for(uint i=0;i<8;i++)v|=ulong(p[i])<<(8*i);return v; }
inline int bcdec__bitstream_read_bits(thread bcdec__bitstream_t* b,int n) { if(!n)return 0;ulong mask=(1ul<<n)-1;int v=int(b->low&mask);b->low=(b->low>>n)|((b->high&mask)<<(64-n));b->high>>=n;return v; }
inline int bcdec__bitstream_read_bit(thread bcdec__bitstream_t* b) { return bcdec__bitstream_read_bits(b,1); }
inline int bcdec__bitstream_read_bits_r(thread bcdec__bitstream_t* b,int n) { int bits=bcdec__bitstream_read_bits(b,n),v=0;while(n--){v=(v<<1)|(bits&1);bits>>=1;}return v; }
'''
kernel = '''
struct BC6Params { uint stride,width,height,x,y,format; };
kernel void decode_bc6(device const uchar* source[[buffer(0)]],constant BC6Params& p[[buffer(1)]],texture2d<float,access::write> target[[texture(0)]],uint2 block[[thread_position_in_grid]]) {
 uint2 base=block*4;if(base.x>=p.width||base.y>=p.height||(p.format!=7&&p.format!=8))return;
 ushort rgb[48];decode_block(source+ulong(block.y)*p.stride+ulong(block.x)*16,rgb,12,p.format==8);
 for(uint y=0;y<4;y++)for(uint x=0;x<4;x++){uint2 q=base+uint2(x,y);if(q.x>=p.width||q.y>=p.height)continue;uint i=(y*4+x)*3;
 target.write(float4(float(as_type<half>(rgb[i])),float(as_type<half>(rgb[i+1])),float(as_type<half>(rgb[i+2])),1),q+uint2(p.x,p.y));}
}
'''
license_text = s[s.index('Copyright (c) 2022 Sergii Kudlai'):s.index('\n------------------------------------------------------------------------------\nALTERNATIVE B')]
notice = '// Generated by scripts/generate-de-bc6-metal.py from locally corrected MIT bcdec.\n/* ' + license_text.strip() + ' */\n'
(root / 'port/de/BC6Kernel.metal').write_text(notice + prefix + helpers + '\n'.join(constants) + '\n' + f + kernel)
